# Generated by Django 5.2.10 on 2026-01-13 20:58

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('category', models.CharField(max_length=100)),
                ('duration_days', models.PositiveIntegerField(help_text='Project duration in days', validators=[django.core.validators.MinValueValidator(1)])),
                ('total_project_value', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('total_shares', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('share_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('shares_sold', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING', 'Pending Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('NEEDS_CHANGES', 'Needs Changes'), ('ARCHIVED', 'Archived')], default='DRAFT', max_length=20)),
                ('restricted_fields', models.JSONField(blank=True, default=dict)),
                ('is_3d_restricted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('developer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectMedia',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('IMAGE', 'Image'), ('MODEL_3D', '3D Model')], max_length=20)),
                ('file', models.FileField(upload_to='projects/%Y/%m/')),
                ('is_restricted', models.BooleanField(default=False)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='projects.project')),
            ],
            options={
                'ordering': ['uploaded_at'],
            },
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['status', '-created_at'], name='projects_pr_status_b6b628_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['developer', 'status'], name='projects_pr_develop_eb4507_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['category', 'status'], name='projects_pr_categor_2f76f8_idx'),
        ),
        migrations.AddIndex(
            model_name='projectmedia',
            index=models.Index(fields=['project', 'type'], name='projects_pr_project_f84cb1_idx'),
        ),
    ]
