# Generated by Django 6.0 on 2026-01-07 11:59

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('category', models.CharField(max_length=100)),
                ('total_project_value', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('total_shares', models.PositiveIntegerField(default=0)),
                ('share_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('shares_sold', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING', 'Pending Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('NEEDS_CHANGES', 'Needs Changes'), ('ARCHIVED', 'Archived')], default='DRAFT', max_length=20)),
                ('restricted_fields', models.JSONField(blank=True, default=dict)),
                ('is_3d_restricted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectMedia',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('IMAGE', 'Image'), ('MODEL_3D', '3D Model')], default='IMAGE', max_length=20)),
                ('file', models.FileField(upload_to='projects/')),
                ('is_restricted', models.BooleanField(default=False)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['uploaded_at'],
            },
        ),
    ]
