# Generated by Django 6.0.1 on 2026-01-22 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_alter_project_share_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='restricted_fields',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='projectmedia',
            name='type',
            field=models.CharField(choices=[('IMAGE', 'Image'), ('VIDEO', 'Video'), ('MODEL', '3D Model')], max_length=20),
        ),
    ]
