# Generated by Django 6.0 on 2026-01-07 11:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('investments', '0001_initial'),
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='sharepurchase',
            name='investor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='share_purchases', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sharepurchase',
            name='payment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='share_purchase', to='investments.paymenttransaction'),
        ),
        migrations.AddField(
            model_name='sharepurchase',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='share_purchases', to='projects.project'),
        ),
    ]
