# Generated by Django 5.2.10 on 2026-01-13 21:51

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0002_initial'),
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paymenttransaction',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='sharepurchase',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='paymenttransaction',
            name='raw_payload',
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='failure_reason',
            field=models.TextField(blank=True, help_text='Reason for payment failure if applicable', null=True),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='gateway_payload',
            field=models.JSONField(blank=True, help_text='Raw payload from payment gateway for debugging', null=True),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='investor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='payment_transactions', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='processed_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when payment was confirmed or failed', null=True),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='payment_transactions', to='projects.project'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='paymenttransaction',
            name='reference_id',
            field=models.CharField(db_index=True, help_text='Unique reference for idempotency and gateway tracking', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='paymenttransaction',
            name='status',
            field=models.CharField(choices=[('INITIATED', 'Payment Initiated'), ('SUCCESS', 'Payment Successful'), ('FAILED', 'Payment Failed')], db_index=True, default='INITIATED', max_length=20),
        ),
        migrations.AlterField(
            model_name='sharepurchase',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='sharepurchase',
            name='payment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='share_purchase', to='investments.paymenttransaction'),
        ),
        migrations.AlterField(
            model_name='sharepurchase',
            name='price_per_share',
            field=models.DecimalField(decimal_places=2, help_text='Price per share at time of purchase', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AlterField(
            model_name='sharepurchase',
            name='shares_purchased',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='sharepurchase',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, help_text='Total amount paid (shares × price_per_share)', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AddIndex(
            model_name='paymenttransaction',
            index=models.Index(fields=['reference_id'], name='payment_tra_referen_87720b_idx'),
        ),
        migrations.AddIndex(
            model_name='paymenttransaction',
            index=models.Index(fields=['investor', 'status'], name='payment_tra_investo_efe8d0_idx'),
        ),
        migrations.AddIndex(
            model_name='paymenttransaction',
            index=models.Index(fields=['project', 'status'], name='payment_tra_project_1857bd_idx'),
        ),
        migrations.AddIndex(
            model_name='sharepurchase',
            index=models.Index(fields=['investor', '-created_at'], name='share_purch_investo_e0817c_idx'),
        ),
        migrations.AddIndex(
            model_name='sharepurchase',
            index=models.Index(fields=['project', '-created_at'], name='share_purch_project_413bb2_idx'),
        ),
        migrations.AlterModelTable(
            name='paymenttransaction',
            table='payment_transactions',
        ),
        migrations.AlterModelTable(
            name='sharepurchase',
            table='share_purchases',
        ),
    ]
