# Generated by Django 4.2.11 on 2026-01-16 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0003_alter_paymenttransaction_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymenttransaction',
            name='failure_reason',
            field=models.TextField(blank=True, help_text='Reason for payment failure if applicable'),
        ),
    ]
