# Generated by Django 6.0.1 on 2026-01-19 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0004_alter_paymenttransaction_failure_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymenttransaction',
            name='shares_requested',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
