# Generated by Django 6.0.1 on 2026-01-20 03:45

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0005_paymenttransaction_shares_requested'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymenttransaction',
            name='amount',
            field=models.DecimalField(decimal_places=2, help_text='Total amount for the transaction', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AlterField(
            model_name='paymenttransaction',
            name='shares_requested',
            field=models.PositiveIntegerField(default=0, help_text='Number of shares requested in this transaction', validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
