# Generated by Django 6.0.1 on 2026-01-27 08:25

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0007_comprehensive_schema_update'),
        ('projects', '0003_alter_project_restricted_fields_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paymenttransaction',
            options={'ordering': ['-created_at'], 'verbose_name': 'Payment Transaction', 'verbose_name_plural': 'Payment Transactions'},
        ),
        migrations.AlterModelOptions(
            name='sharepurchase',
            options={'ordering': ['-created_at'], 'verbose_name': 'Share Purchase', 'verbose_name_plural': 'Share Purchases'},
        ),
        migrations.RemoveIndex(
            model_name='paymenttransaction',
            name='payment_tra_project_1857bd_idx',
        ),
        migrations.RenameIndex(
            model_name='paymenttransaction',
            new_name='investments_investo_60dde0_idx',
            old_name='payment_tra_investo_efe8d0_idx',
        ),
        migrations.RenameIndex(
            model_name='paymenttransaction',
            new_name='investments_referen_a4396a_idx',
            old_name='payment_tra_referen_87720b_idx',
        ),
        migrations.RenameIndex(
            model_name='paymenttransaction',
            new_name='investments_idempot_fab01f_idx',
            old_name='investments_idempot_key_idx',
        ),
        migrations.RenameIndex(
            model_name='sharepurchase',
            new_name='investments_investo_1d36d7_idx',
            old_name='share_purch_investo_e0817c_idx',
        ),
        migrations.RenameIndex(
            model_name='sharepurchase',
            new_name='investments_project_da6a5f_idx',
            old_name='share_purch_project_413bb2_idx',
        ),
        migrations.AlterField(
            model_name='paymenttransaction',
            name='amount',
            field=models.DecimalField(decimal_places=2, help_text='Amount in USD', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AlterField(
            model_name='paymenttransaction',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, help_text='When payment was initiated'),
        ),
        migrations.AlterField(
            model_name='paymenttransaction',
            name='failure_reason',
            field=models.TextField(blank=True, help_text='Error message if payment failed', null=True),
        ),
        migrations.AlterField(
            model_name='paymenttransaction',
            name='gateway_payload',
            field=models.JSONField(blank=True, help_text='Complete response from payment gateway (for audit)', null=True),
        ),
        migrations.AlterField(
            model_name='paymenttransaction',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique transaction identifier', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='paymenttransaction',
            name='processed_at',
            field=models.DateTimeField(blank=True, help_text='When payment was processed by gateway', null=True),
        ),
        migrations.AlterField(
            model_name='paymenttransaction',
            name='reference_id',
            field=models.CharField(db_index=True, help_text='Unique reference from payment gateway', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='paymenttransaction',
            name='shares_requested',
            field=models.PositiveIntegerField(help_text='Number of shares requested', validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='paymenttransaction',
            name='status',
            field=models.CharField(choices=[('INITIATED', 'Payment Initiated'), ('SUCCESS', 'Payment Successful'), ('FAILED', 'Payment Failed')], db_index=True, default='INITIATED', help_text='Current payment status', max_length=20),
        ),
        migrations.AlterField(
            model_name='sharepurchase',
            name='payment_transaction',
            field=models.OneToOneField(help_text='Associated successful payment', on_delete=django.db.models.deletion.PROTECT, related_name='share_purchase', to='investments.paymenttransaction'),
        ),
        migrations.AlterField(
            model_name='sharepurchase',
            name='price_per_share',
            field=models.DecimalField(decimal_places=2, help_text='Price per share at time of purchase (immutable)', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AlterField(
            model_name='sharepurchase',
            name='shares_purchased',
            field=models.PositiveIntegerField(help_text='Number of shares purchased', validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='sharepurchase',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, help_text='Total amount = shares × price', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AddIndex(
            model_name='paymenttransaction',
            index=models.Index(fields=['project', '-created_at'], name='investments_project_10d171_idx'),
        ),
        migrations.AlterModelTable(
            name='paymenttransaction',
            table='investments_payment_transaction',
        ),
        migrations.AlterModelTable(
            name='sharepurchase',
            table='investments_share_purchase',
        ),
    ]
