# Generated by Django 6.0.1 on 2026-01-27 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0008_alter_paymenttransaction_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymenttransaction',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='When payment was last updated'),
        ),
    ]
