# Generated by Django 4.2.11 on 2026-01-27 19:03

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0003_alter_project_restricted_fields_and_more'),
        ('investments', '0009_paymenttransaction_updated_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvestmentRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('requested_shares', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('price_per_share', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('status', models.CharField(choices=[('PENDING_PAYMENT', 'Pending Payment'), ('PAYMENT_FAILED', 'Payment Failed'), ('PAYMENT_CONFIRMED', 'Payment Confirmed'), ('ADMIN_APPROVED', 'Admin Approved'), ('ADMIN_REJECTED', 'Admin Rejected'), ('SHARES_ALLOCATED', 'Shares Allocated'), ('CANCELLED', 'Cancelled')], db_index=True, default='PENDING_PAYMENT', max_length=30)),
                ('payment_reference', models.CharField(db_index=True, max_length=255, unique=True)),
                ('payment_url', models.URLField(blank=True, max_length=1000, null=True)),
                ('admin_remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'investments_investment_request',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PortfolioHolding',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('shares_owned', models.PositiveIntegerField(default=0)),
                ('avg_buy_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'investments_portfolio_holding',
            },
        ),
        migrations.CreateModel(
            name='ShareLedger',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('shares_delta', models.IntegerField(help_text='Positive for purchase, negative for withdrawal/refund')),
                ('reason', models.CharField(choices=[('PURCHASE', 'Purchase'), ('REFUND', 'Refund'), ('ADJUSTMENT', 'Adjustment')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'db_table': 'investments_share_ledger',
            },
        ),
        migrations.AlterModelOptions(
            name='paymenttransaction',
            options={},
        ),
        migrations.AlterModelOptions(
            name='sharepurchase',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='paymenttransaction',
            name='investments_referen_a4396a_idx',
        ),
        migrations.RemoveIndex(
            model_name='paymenttransaction',
            name='investments_investo_60dde0_idx',
        ),
        migrations.RemoveIndex(
            model_name='paymenttransaction',
            name='investments_idempot_fab01f_idx',
        ),
        migrations.RemoveIndex(
            model_name='paymenttransaction',
            name='investments_project_10d171_idx',
        ),
        migrations.RemoveIndex(
            model_name='sharepurchase',
            name='investments_investo_1d36d7_idx',
        ),
        migrations.RemoveIndex(
            model_name='sharepurchase',
            name='investments_project_da6a5f_idx',
        ),
        migrations.RemoveField(
            model_name='paymenttransaction',
            name='failure_reason',
        ),
        migrations.RemoveField(
            model_name='paymenttransaction',
            name='gateway_payload',
        ),
        migrations.RemoveField(
            model_name='paymenttransaction',
            name='idempotency_key',
        ),
        migrations.RemoveField(
            model_name='paymenttransaction',
            name='investor',
        ),
        migrations.RemoveField(
            model_name='paymenttransaction',
            name='processed_at',
        ),
        migrations.RemoveField(
            model_name='paymenttransaction',
            name='project',
        ),
        migrations.RemoveField(
            model_name='paymenttransaction',
            name='reference_id',
        ),
        migrations.RemoveField(
            model_name='paymenttransaction',
            name='shares_requested',
        ),
        migrations.RemoveField(
            model_name='sharepurchase',
            name='payment_transaction',
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='currency',
            field=models.CharField(default='USD', max_length=10),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='gateway_transaction_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='raw_gateway_response',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='paymenttransaction',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
        migrations.AlterField(
            model_name='paymenttransaction',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='paymenttransaction',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='paymenttransaction',
            name='status',
            field=models.CharField(choices=[('INITIATED', 'Initiated'), ('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('REFUNDED', 'Refunded')], db_index=True, default='INITIATED', max_length=20),
        ),
        migrations.AlterField(
            model_name='paymenttransaction',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='sharepurchase',
            name='investor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='share_purchases', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='sharepurchase',
            name='price_per_share',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='sharepurchase',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='share_purchases', to='projects.project'),
        ),
        migrations.AlterField(
            model_name='sharepurchase',
            name='shares_purchased',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='sharepurchase',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
        migrations.AddField(
            model_name='shareledger',
            name='investment_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ledger_entries', to='investments.investmentrequest'),
        ),
        migrations.AddField(
            model_name='shareledger',
            name='investor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ledger_entries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='shareledger',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ledger_entries', to='projects.project'),
        ),
        migrations.AddField(
            model_name='portfolioholding',
            name='investor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='portfolio_holdings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='portfolioholding',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='portfolio_holdings', to='projects.project'),
        ),
        migrations.AddField(
            model_name='investmentrequest',
            name='investor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='investment_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='investmentrequest',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='investment_requests', to='projects.project'),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='investment_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='investments.investmentrequest'),
        ),
        migrations.AddField(
            model_name='sharepurchase',
            name='investment_request',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='share_purchase', to='investments.investmentrequest'),
        ),
        migrations.AlterUniqueTogether(
            name='portfolioholding',
            unique_together={('investor', 'project')},
        ),
        migrations.AddIndex(
            model_name='investmentrequest',
            index=models.Index(fields=['investor', 'status'], name='investments_investo_dc7c1a_idx'),
        ),
        migrations.AddIndex(
            model_name='investmentrequest',
            index=models.Index(fields=['project', 'status'], name='investments_project_161caa_idx'),
        ),
    ]
