# Generated by Django 6.0.1 on 2026-01-28 09:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0012_populate_reference_ids'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymenttransaction',
            name='reference_id',
            field=models.CharField(db_index=True, default='', help_text='Unique reference from payment gateway', max_length=255, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sharepurchase',
            name='payment_transaction',
            field=models.OneToOneField(default=1, help_text='Associated successful payment', on_delete=django.db.models.deletion.PROTECT, related_name='share_purchase', to='investments.paymenttransaction'),
            preserve_default=False,
        ),
    ]
