# Required metadata
sonar.projectKey=crowdfunding
sonar.projectName=Crowdfunding Platform
sonar.projectVersion=1.0

# Source code location
sonar.sources=apps

# Exclude unnecessary files/folders
sonar.exclusions=**/migrations/**,**/tests/**,venv/**

# Language & encoding
sonar.language=py
sonar.sourceEncoding=UTF-8
