# Generated by Django 6.0 on 2026-01-01 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='verification_token',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='verification_token_expiry',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
