# Generated by Django 4.2.11 on 2026-01-27 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0006_alter_auditlog_actor'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='after_state',
            field=models.JSONField(blank=True, help_text='State of entity after action', null=True),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='before_state',
            field=models.JSONField(blank=True, help_text='State of entity before action', null=True),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
