# Generated by Django 6.0.1 on 2026-01-22 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_notification_metadata_notification_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('PROJECT_SUBMITTED', 'Project Submitted'), ('PROJECT_APPROVED', 'Project Approved'), ('PROJECT_REJECTED', 'Project Rejected'), ('PROJECT_CHANGES_REQUESTED', 'Project Changes Requested'), ('PAYMENT_SUCCESS', 'Payment Success'), ('PAYMENT_FAILED', 'Payment Failed'), ('PAYMENT_PENDING', 'Payment Pending'), ('ACCESS_APPROVED', 'Access Approved'), ('ACCESS_REJECTED', 'Access Rejected'), ('ACCESS_REQUESTED', 'Access Requested'), ('ACCESS_REVOKED', 'Access Revoked'), ('SYSTEM', 'System')], max_length=30),
        ),
    ]
